remote_theme: mikearnaldi/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
'effect-http on GitHub':
  - 'https://sukovanej.github.io/effect-http'