remote_theme: mikearnaldi/just-the-docs

# Enable or disable the site search
search_enabled: true

plugins:
  - jemoji

# Aux links for the upper right navigation
aux_links:
  'GitHub':
    - 'https://github.com/sukovanej/effect-http'
